#!/bin/bash

echo "Funding Your Base Sepolia Wallet"
echo "===================================="
echo ""
echo "Your wallet address: ${TEST_WALLET_ADDRESS}"
echo ""
echo "Step 1: Get Base Sepolia ETH"
echo "Visit: https://www.coinbase.com/faucets/base-ethereum-goerli-faucet"
echo "Enter address: ${TEST_WALLET_ADDRESS}"
echo ""
echo "Step 2: Get USDC on Base Sepolia"
echo "Option A: Bridge from Ethereum Sepolia"
echo "  1. Get Sepolia USDC from faucet"
echo "  2. Bridge to Base Sepolia via Coinbase bridge"
echo ""
echo "Option B: Use USDC faucet (if available)"
echo ""
echo "USDC Contract: 0x036CbD53842c5426634e7929541eC2318f3dCF7e"
echo ""
echo "Check balance:"
echo "  ETH:  cast balance $TEST_WALLET_ADDRESS --rpc-url $BASE_SEPOLIA_RPC_URL"
echo "  USDC: cast call 0x036CbD53842c5426634e7929541eC2318f3dCF7e 'balanceOf(address)(uint256)' $TEST_WALLET_ADDRESS --rpc-url $BASE_SEPOLIA_RPC_URL"

